#!/usr/bin/python
import subprocess
try:
    print "[!] SET is changing to just ./setoolkit instead"
    print "[!] se-toolkit is going away, beware."
    print "[!] Use: ./setoolkit from now on."
    raw_input("Press {return} to continue.")
    subprocess.Popen("./setoolkit", shell=True).wait()

# handle keyboard interrupts
except KeyboardInterrupt:
    print "\n\nThank you for " + bcolors.RED+"shopping" + bcolors.ENDC+" with the Social-Engineer Toolkit.\n\nHack the Gibson...and remember...hugs are worth more than handshakes.\n"

# handle exceptions
except Exception, error:
    log(error)
    print "\n\n[!] Something went wrong, printing the error: "+ str(error)
