#!/usr/bin/env python
import sys,socket
try:
        # import the web interface
        from src.commandcenter.command_center import *

# except socket errors
except socket.error:
        print "[*] Something is already running on the SET web port, please exit it and then restart.\n\n"

# except os errors
except OSError:
        pass

# except the rest
except: 
        print "[*] Exiting the Social-Engineer Toolkit Command-Center"
        print "[*] Thank you for shopping at the Social-Engineer Toolkit\n"
        pass
