#!/usr/bin/env python
#
# simple svn update for set pulling from core modules
#
import os
import sys

# check where we are and load default directory
if os.path.isdir("/usr/share/setoolkit"):
    if not os.path.isfile("se-toolkit"):
        os.chdir("/usr/share/setoolkit")
        sys.path.append("/usr/share/setoolkit")

# if we can't see our config then something didn't go good..
if not os.path.isfile("/etc/setoolkit/set.config"):
    print_error("Cannot locate SET executable. Try running from the local directory.")
    print_error("If this does not work, please run the setup.py install file.")
    sys.exit()

from src.core.setcore import *

try:
    # pull update set from the core libraries
    update_set()

# except keyboard interrupts
except KeyboardInterrupt:
    print "\n[!] Control-C detected. Exiting updating SET."

# handle all other errors
except Exception, e: print "\n[!] Something went wrong.. Printing the error: " + e
